module Environments
  APK ||= 'apk'
  PACKAGE ||= 'package'
  PORT ||= 'PORT'
  SIMULATOR ||= 'SIMULATOR'
  DEVICE ||= 'DEVICE'
  APP_LOCATION ||= 'AppLocation'
  IPA ||= 'ipa'
  RECORD_SCREEN ||= 'recordScreen'
  START_APPIUM ||= 'START_APPIUM'
  APPIUM_PARAMETERS ||= 'APPIUM_PARAMETERS'
  UDID ||= 'udid'
  APP_URL ||= 'app_url'
  IOS_LOCAL ||= 'ios_local'
  IOS_EXTERNAL ||= 'ios_external'
  ANDROID_LOCAL ||= 'android_local'
  ANDROID_EXTERNAL ||= 'android_external'
end